PlotAppMVC/Controllers/AuctionController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.Dtos;
using Models.Entities;
using Services;

namespace PlotAppMVC.Controllers
{
    [Authorize]
    public class AuctionController : Controller
    {
        private readonly IAuctionService _auctionService;
        private readonly IAccountService _accountService;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _hostEnvironment;

        public AuctionController(IAuctionService auctionService
            , IAccountService accountService
            , IMapper mapper, IWebHostEnvironment hostEnvironment)
        {
            _auctionService = auctionService;
            _accountService = accountService;
            _mapper = mapper;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet("/auction")]
        public ActionResult Index([FromQuery] Query query)
        {
            var auctions = _auctionService.GetAuctions(query);

            ViewData["auctions"] = auctions;
            return View();
        }

        [HttpGet("/admin/auctions")]
        [Authorize(Roles = "Admin, Owner")]
        public ActionResult ManageAuctions([FromQuery] Query query)
        {
            var auctions = _auctionService.GetAuctions(query, true, null);

            ViewData["auctions"] = auctions;
            return View("ManageAuctions");
        }

        [HttpGet("/auction/user")]
        public ActionResult UserAuctions([FromQuery] Query query)
        {
            var userId = User?.Identity?.GetUserId();

            var auctions = _auctionService.GetAuctions(query, false, userId);

            ViewData["auctions"] = auctions;
            return View("UserAuctions");
        }

        [HttpGet("/auction/{auctionId}/details")]
        public async Task<ActionResult> Details(string auctionId)
        {
            var result = _auctionService.GetAuction(auctionId);

            var userId = User?.Identity?.GetUserId();
            var user = await _accountService.GetUserById(userId);

            ViewData["user"] = user;
            return View(result);
        }

        [HttpGet("/auction/create")]
        public ActionResult Create()
        {
            var categories = _auctionService.GetAllCategories();

            ViewData["categories"] = categories;
            return View();
        }

        // POST: AuctionController/Create
        [HttpPost("/auction/create")]
        public async Task<ActionResult> Create(ItemDto dto)
        {
            var categories = _auctionService.GetAllCategories();
            ViewData["categories"] = categories;

            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            var userId = User?.Identity?.GetUserId();

            var imageName = await SaveImage(dto);

            dto.ImageName = imageName;

            var auction = await _auctionService.CreateAuction(dto, userId);

            if (auction)
            {
                TempData["Success"] = "Auction added";
                return Redirect("/auction/user");
            }

            TempData["Error"] = "Auction creating failed";
            return View(dto);
        }

        [HttpGet("/auction/{auctionId}/edit")]
        public ActionResult Edit(string auctionId)
        {
            var auction = _auctionService.GetAuction(auctionId);
            if(auction is null)
            {
                TempData["Error"] = "Auction not found";
                return Redirect("/auction");
            }

            var categories = _auctionService.GetAllCategories();
            ViewData["categories"] = categories;

            var auctionDto = _mapper.Map<ItemDto>(auction);
            return View(auctionDto);
        }

        [HttpPost("/auction/{auctionId}/edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([FromForm] ItemDto dto, [FromRoute] string auctionId)
        {
            dto.Id = auctionId;

            var categories = _auctionService.GetAllCategories();
            ViewData["categories"] = categories;

            if (!ModelState.IsValid)
            {
                return View(dto);
            }

            var userId = User?.Identity?.GetUserId();

            var auctionUpdated = await _auctionService.UpdateAuction(auctionId, dto, userId);

            if (auctionUpdated)
            {
                TempData["Success"] = "Auction Updated Successfully";
                return Redirect("/auction/user");
            }

            TempData["Error"] = "Auction Update Failed";
            return View(dto);
        }

        [HttpGet("/auction/{auctionId}/delete")]
        public ActionResult DeleteConfirm([FromRoute]string auctionId)
        {
            var auction = _auctionService.GetAuction(auctionId);
            ViewData["auction"] = auction;

            return View("ConfirmDeleteAuction");
        }

        [HttpPost("/auction/{auctionId}/delete/confirmed")]
        public async Task<ActionResult> Delete([FromRoute] string auctionId)
        {
            var userId = User?.Identity?.GetUserId();

            var auction = _auctionService.GetAuction(auctionId);
            var deletedAuction = await _auctionService.DeleteAuction(auctionId, userId);



            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "Image", auction.ImageName);

            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }


            if (deletedAuction)
            {
                TempData["Success"] = "Auction Deleted";
            }
            else
            {
                TempData["Error"] = "Auction delete failed";
            }

            return Redirect("/auction/user");
        }

        [HttpGet("/auction/category")]
        public ActionResult Categories()
        {
            var result = _auctionService.GetAllCategories();
            ViewData["categories"] = result;

            return View("Categories");
        }

        [HttpPost("/auction/category/create")]
        public async Task<ActionResult> CreateCategory([FromForm] CategoryModel category)
        {
            var result = _auctionService.GetAllCategories();
            ViewData["categories"] = result;

            if (!ModelState.IsValid)
            {
                return View("Categories", category);
            }
            var newCategory = await _auctionService.CreateCategory(category);

            if (newCategory)
            {
                TempData["Success"] = "Category created";
                return Redirect("/auction/category");
            }

            TempData["Error"] = "Category creating failed";
            return View("Categories");
        }

        [HttpPost("/auction/category/{categoryId}")]
        public async Task<ActionResult> DeleteCategory([FromRoute]string categoryId)
        {
            var deletedCategory = await _auctionService.DeleteCategory(categoryId);

            var result = _auctionService.GetAllCategories();
            ViewData["categories"] = result;

            if (deletedCategory)
            {
                TempData["Success"] = "Category deleted";
                return Redirect("/auction/category");
            }

            TempData["Error"] = "Category deleting failed";
            return View("Categories");
        }

        public async Task<string> SaveImage(ItemDto dto)
        {
            try
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(dto.ImageFile.FileName);
                string extension = Path.GetExtension(dto.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/" + fileName);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await dto.ImageFile.CopyToAsync(fileStream);
                }

                return fileName;
            }catch (Exception ex)
            {
                return "";
            }
            
        }
    }
}

PlotAppMVC/Controllers/PlotController.cs
using Microsoft.AspNetCore.Mvc;
using Services;
using Microsoft.JSInterop;
using Microsoft.AspNet.Identity;
using Models.Entities;
using Services.ApiFiles;
using Microsoft.AspNetCore.Authorization;
using MongoDB.Bson;
using Models.Dtos;
using System.Diagnostics;

namespace PlotAppMVC.Controllers
{
    [Authorize]
    public class PlotController : Controller
    {
        private readonly IPlotService _plotService;

        public PlotController(IPlotService plotService)
        {
            _plotService = plotService;
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Index()
        {
            return View("Index");
        }

        [HttpGet("/plots")]
        public async Task<List<PlotModel>> GetUserPlots([FromQuery] string searchText)
        {
            var userId = User.Identity.GetUserId();
            var plots = await _plotService.GetUsersPlots(userId, searchText);

            return plots;
        }

        [HttpPost("/plot")]
        public async Task<ActionResult> AddPlot([FromForm]PlotDto model)
        {
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Invalid input";
                return View("Index", model);
            }

            var userId = User.Identity.GetUserId();

            var result = await _plotService.CreatePlot(model, userId);

            if (result)
            {
                TempData["Success"] = "Plot Added";
            }
            else
            {
                TempData["Error"] = "Plot not found";
            }

            return Redirect("/");
        }

        [HttpPost("/plot/{id}")]
        public async Task<ActionResult> DeletePlot([FromRoute]string id)
        {
            var userId = User.Identity.GetUserId();

            var result = await _plotService.DeletePlot(id, userId);

            TempData["Success"] = "Plot Deleted Successfully";

            return Redirect("/");
        }

        [HttpGet("/plot/{id}/edit")]
        public async Task<ActionResult> EditPlot(string id)
        {
            var plot = await _plotService.GetPlot(id);

            return View(plot);
        }

        [HttpPost("/plot/{id}/edit")]
        public async Task<ActionResult> EditPlot([FromRoute] string id, [FromForm] PlotModel model)
        {
            model.Id = id;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = User.Identity.GetUserId();

            var plotUpdated = await _plotService.UpdatePlot(id, model, userId);

            if (plotUpdated)
            {
                TempData["Success"] = "Plot Updated Successfully";
                return View("Index");
            }

            TempData["Error"] = "Plot Update Failed";
            return View(model);
        }

        [Route("/Error")]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PlotAppMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlotAppMVC</title>
    <link 
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" 
  rel="stylesheet"  type='text/css'>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlotAppMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
   integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
   crossorigin=""/>
   <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
   integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
   crossorigin=""></script>
   <script src="~/script.js"></script>
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom text-white box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Plot" asp-action="Index">PlotAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Plot" asp-action="Index">Plots Map</a>
                        </li>
                        @if(User?.Identity?.IsAuthenticated ?? false)
                        {

                            <li class="nav-item">
                            <a class="nav-link text-light" href="/profile/@User.Identity.GetUserId()">Profile</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Auction" asp-action="Index">Auctions</a>
                            </li>

                            @if (User.IsInRole("Owner"))
                            {

                                <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Admin">Admin Dashboard</a>
                            </li>

                            }
                            
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1 justify-content-end mx-5">
                        @if(User?.Identity?.IsAuthenticated ?? false)
                        {                         
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            
                        }
                        else
                        {
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section class="bg-dark d-flex justify-content-center align-items-center"  style="height: 80vh;">
            <main role="main" class="d-flex justify-content-center align-items-centers w-100 h-100">
    <partial name="_Notification" />
                @RenderBody()
            </main>
    </section>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2022 - PlotAppMVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PlotAppMVC/Views/Shared/_Notification.cshtml
          
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (@TempData["Success"] != null)
    {

        <script type="text/javascript">
                toastr.success('@TempData["Success"]');
        </script>
    }
@if (@TempData["Error"] != null)
    {

        <script type="text/javascript">
                toastr.error('@TempData["Error"]');
        </script>
    }